version: '3.8'

services:

  app:
    build: .
    command: uvicorn API.main:app --reload --host 0.0.0.0 --port 8000 --no-use-colors --proxy-headers
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - redis

  worker:
    build: .
    command: celery --app API.api_worker worker --loglevel=DEBUG
    volumes:
      - .:/app
    depends_on:
      - app
      - redis

  redis:
    image: redis:6-alpine
    ports:
     - "6379:6379"

  worker-dashboard:
    build: .
    command:  celery --app API.api_worker flower --port=5550 --broker=redis://redis:6379/
    ports:
      - 5550:5550
    depends_on:
      - app
      - redis
      - worker