version: '3.8'

services:

  postgres:
      image: postgis/postgis
      container_name: pgsql
      environment:
        - POSTGRES_MULTIPLE_DATABASES="underpass","tm","raw","insights"
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=admin
      ports:
        - '5434:5432'
      volumes:
        - ./tests/src/fixtures/:/sql/
        - ./postgres-data:/var/lib/postgresql/data
        - ./docker-multiple-db.sh:/docker-entrypoint-initdb.d/create.sh
        - ./populate-docker-db.sh:/docker-entrypoint-initdb.d/insert.sh


  app:
    build: .
    container_name: api
    command: uvicorn API.main:app --reload --host 0.0.0.0 --port 8000 --no-use-colors --proxy-headers
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres


  worker:
    build: .
    container_name: worker
    command: celery --app API.api_worker worker --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - app
      - redis
      - postgres

  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
     - "6379:6379"

  worker-dashboard:
    build: .
    container_name: flower
    command:  celery --app API.api_worker flower --port=4000 --broker=redis://redis:6379/
    ports:
      - 4000:4000
    depends_on:
      - app
      - redis
      - worker